/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pk.codeapp.screen;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import pk.codeapp.methods.GameSettings;
import pk.codeapp.model.Attack;
import pk.codeapp.model.GraphicsElement;
import pk.codeapp.model.Path;
import pk.codeapp.model.Titan;
import pk.codeapp.model.Tower;

/**
 *
 * @author Jose Pablo Brenes
 */
public class AuxAttackMode extends javax.swing.JFrame
{

    private Titan titan;
    private GraphicsElement element;
    private DefaultComboBoxModel<String> listAttacks = new DefaultComboBoxModel();
    private Game window;

    private GameSettings gameSettings = new GameSettings(MainApp.methods);
    private String arena;

    public AuxAttackMode()
    {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cmbSpecialAttack = new javax.swing.JComboBox<>();
        btnMakeAttack = new javax.swing.JButton();
        lblActual = new javax.swing.JLabel();
        lblArrow = new javax.swing.JLabel();
        lblDefended = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 137, 123));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select the attack you want to perform");

        cmbSpecialAttack.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmbSpecialAttack.setForeground(new java.awt.Color(255, 255, 255));
        cmbSpecialAttack.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " " }));

        btnMakeAttack.setBackground(new java.awt.Color(0, 0, 0));
        btnMakeAttack.setForeground(new java.awt.Color(255, 255, 255));
        btnMakeAttack.setText("Make Attack");
        btnMakeAttack.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnMakeAttackActionPerformed(evt);
            }
        });

        lblActual.setBorder(new javax.swing.border.MatteBorder(null));
        lblActual.setMaximumSize(new java.awt.Dimension(80, 80));
        lblActual.setMinimumSize(new java.awt.Dimension(80, 80));
        lblActual.setPreferredSize(new java.awt.Dimension(80, 80));

        lblArrow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pk/codeapp/tools/arrow.png"))); // NOI18N

        lblDefended.setBorder(new javax.swing.border.MatteBorder(null));
        lblDefended.setMaximumSize(new java.awt.Dimension(80, 80));
        lblDefended.setMinimumSize(new java.awt.Dimension(80, 80));
        lblDefended.setPreferredSize(new java.awt.Dimension(80, 80));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(lblActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(lblArrow)
                        .addGap(51, 51, 51)
                        .addComponent(lblDefended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(85, 85, 85)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(189, 189, 189)
                        .addComponent(cmbSpecialAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(btnMakeAttack)))
                .addContainerGap(88, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDefended, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblArrow, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(cmbSpecialAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnMakeAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMakeAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeAttackActionPerformed
        String attackName = (String) cmbSpecialAttack.getSelectedItem();

        Attack attack = searchAttack(attackName);

        if (attack != null) {
            System.out.println("Entrando");
             lblDefended.setIcon(new ImageIcon("src/pk/codeapp/tools/explosion.gif"));
            gameSettings.attack(titan, element, attack, arena); //need send attack
           
            try {
               
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
              
                Thread.currentThread().interrupt();
            }
              goBack();
        }
    }//GEN-LAST:event_btnMakeAttackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AuxAttackMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AuxAttackMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AuxAttackMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AuxAttackMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new AuxAttackMode().setVisible(true);
            }
        });
    }

    public Attack searchAttack(String name)
    {
        for (int i = 0; i < titan.getAttacks().size(); i++) {
            if (titan.getAttacks().get(i).getNameAttack().equals(name)) {

                return titan.getAttacks().get(i);
            }

        }
        return null;
    }

    public void getToolsToAttack(Titan titan, GraphicsElement element, Game window, String arena)
    { // Get tools to make attack
        this.titan = titan;
        this.element = element;
        this.window = window;
        this.setVisible(true);
        window.setEnabled(false);
        this.arena = arena;
        viewAttacks(); // Show attacks in the cmb
        viewTitans();
    }

    private void viewTitans()
    {
        lblActual.setIcon(this.titan.getIcon());
        if (element instanceof Titan) {
            Titan titan = (Titan) element;
            lblDefended.setIcon(titan.getIcon());
        } else {
            lblDefended.setIcon(new ImageIcon("src/pk/codeapp/tools/tower.png"));
        }
    }

    private void viewAttacks()
    {
        listAttacks = new DefaultComboBoxModel();
        for (int i = 0; i < titan.getAttacks().size(); i++) {
            String attack = titan.getAttacks().get(i).getNameAttack();
            listAttacks.addElement(attack);
        }
        cmbSpecialAttack.setModel(listAttacks);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMakeAttack;
    private javax.swing.JComboBox<String> cmbSpecialAttack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblActual;
    private javax.swing.JLabel lblArrow;
    private javax.swing.JLabel lblDefended;
    // End of variables declaration//GEN-END:variables

    private void goBack()
    {
        window.setEnabled(true);

        this.dispose();
        window.changeStates(element);
    }
}
