/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pk.codeapp.screen;

import javax.swing.JFrame;
import pk.codeapp.methods.DefaultRules;
import pk.codeapp.model.Estadistics;
import pk.codeapp.model.User;


/**
 *
 * @author Daniel Amador
 */
public class DataSheet extends javax.swing.JFrame implements DefaultRules
{   
    Lobby beforeWindow;
    Estadistics actual;
    /**
     * Creates new form DataSheet
     */
    public DataSheet()
    {
        initComponents();
        
        User us=MainApp.methods.getActual();
        actual= us.getUserEstadistics();
        System.out.println(actual);
        lblWinGames.setText(actual.getWinGames()+"");
        lblDeadTitans.setText(actual.getDeadTitans()+"");
        
        lblDestroyedTower.setText(actual.getDrestroyTower()+"");
        lblGameLost.setText(actual.getLostGames()+"");
        lblGamesPlayed.setText(actual.getPlayedGames()+"");
        lblPerformance.setText(actual.getPerformance()+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblGameLost = new javax.swing.JLabel();
        lblDestroyedTower = new javax.swing.JLabel();
        lblWinGames = new javax.swing.JLabel();
        lblDeadTitans = new javax.swing.JLabel();
        lblGamesPlayed = new javax.swing.JLabel();
        lblTowerDestroyed = new javax.swing.JLabel();
        lblPerformance = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Number of games lost:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, 30));

        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Number of destroyed tower :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 360, -1, 50));

        jLabel3.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Number of games played:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 30));

        jLabel4.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Number of win games:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, 30));

        jLabel5.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Number of dead Titans:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, 30));

        jLabel6.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Number of own towers destroyed:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Performance:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, -1, -1));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));

        lblGameLost.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblGameLost.setForeground(new java.awt.Color(255, 255, 255));
        lblGameLost.setText("gameLost");
        getContentPane().add(lblGameLost, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, -1, -1));

        lblDestroyedTower.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblDestroyedTower.setForeground(new java.awt.Color(255, 255, 255));
        lblDestroyedTower.setText("destroyedTower");
        getContentPane().add(lblDestroyedTower, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        lblWinGames.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblWinGames.setForeground(new java.awt.Color(255, 255, 255));
        lblWinGames.setText("winGames");
        getContentPane().add(lblWinGames, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 190, -1, -1));

        lblDeadTitans.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblDeadTitans.setForeground(new java.awt.Color(255, 255, 255));
        lblDeadTitans.setText("deadTitans");
        getContentPane().add(lblDeadTitans, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));

        lblGamesPlayed.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblGamesPlayed.setForeground(new java.awt.Color(255, 255, 255));
        lblGamesPlayed.setText("gamesPlayed");
        getContentPane().add(lblGamesPlayed, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, -1, -1));

        lblTowerDestroyed.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTowerDestroyed.setForeground(new java.awt.Color(255, 255, 255));
        lblTowerDestroyed.setText("towersDestroyed");
        getContentPane().add(lblTowerDestroyed, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 460, -1, -1));

        lblPerformance.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblPerformance.setForeground(new java.awt.Color(255, 255, 255));
        lblPerformance.setText("performance");
        getContentPane().add(lblPerformance, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 550, -1, -1));

        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 670, 80, 40));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pk/codeapp/tools/estadistics.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton1ActionPerformed
    {//GEN-HEADEREND:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DataSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DataSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DataSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DataSheet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new DataSheet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblDeadTitans;
    private javax.swing.JLabel lblDestroyedTower;
    private javax.swing.JLabel lblGameLost;
    private javax.swing.JLabel lblGamesPlayed;
    private javax.swing.JLabel lblPerformance;
    private javax.swing.JLabel lblTowerDestroyed;
    private javax.swing.JLabel lblWinGames;
    // End of variables declaration//GEN-END:variables

    @Override
    public void openWindow(JFrame frame)
    {
        this.beforeWindow= (Lobby) frame;
        this.setVisible(true);
        beforeWindow.setVisible(false);
        
    }

    @Override
    public void goBack()
    {
       this.dispose();
       beforeWindow.setVisible(true);
    }
}
