/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pk.codeapp.screen;

import javax.swing.ImageIcon;

/**
 *
 * @author Jose Pablo Brenes
 */
public class SelectTitan extends javax.swing.JFrame {

    /**
     * Creates new form SelectTitan
     */
    public SelectTitan() {
        initComponents();
       lblBackground.setIcon(new ImageIcon("src/pk/codeapp/tools/SelectTitan_Background.jpg")); // Image Background 
       this.setLocationRelativeTo(null); //Localization of Windows
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTitan1 = new javax.swing.ButtonGroup();
        buttonGroupTitan2 = new javax.swing.ButtonGroup();
        buttonGroupTitan3 = new javax.swing.ButtonGroup();
        buttonGroupTitan4 = new javax.swing.ButtonGroup();
        buttonGroupTitan5 = new javax.swing.ButtonGroup();
        buttonGroupTitan6 = new javax.swing.ButtonGroup();
        buttonGroupTitan7 = new javax.swing.ButtonGroup();
        buttonGroupTitan8 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        titan_image6 = new javax.swing.JLabel();
        titan_image1 = new javax.swing.JLabel();
        titan_image3 = new javax.swing.JLabel();
        titan_image2 = new javax.swing.JLabel();
        titan_image4 = new javax.swing.JLabel();
        titan_image8 = new javax.swing.JLabel();
        titan_image5 = new javax.swing.JLabel();
        titan_image7 = new javax.swing.JLabel();
        btnTitan2_Player1 = new javax.swing.JRadioButton();
        btnTitan5_Player1 = new javax.swing.JRadioButton();
        btnTitan3_Player1 = new javax.swing.JRadioButton();
        btnTitan4_Player1 = new javax.swing.JRadioButton();
        btnTitan6_Player1 = new javax.swing.JRadioButton();
        btnTitan7_Player1 = new javax.swing.JRadioButton();
        btnTitan8_Player1 = new javax.swing.JRadioButton();
        btnTitan1_Player1 = new javax.swing.JRadioButton();
        btnTitan2_Player2 = new javax.swing.JRadioButton();
        btnTitan3_Player2 = new javax.swing.JRadioButton();
        btnTitan4_Player2 = new javax.swing.JRadioButton();
        btnTitan5_Player2 = new javax.swing.JRadioButton();
        btnTitan6_Player2 = new javax.swing.JRadioButton();
        btnTitan7_Player2 = new javax.swing.JRadioButton();
        btnTitan8_Player2 = new javax.swing.JRadioButton();
        btnTitan1_Player2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        cmbSizeofmap = new javax.swing.JComboBox<>();
        lblBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1280, 720));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select the Titans");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 290, 50));

        titan_image6.setToolTipText("");
        titan_image6.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 290, 80, 80));

        titan_image1.setToolTipText("");
        titan_image1.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 80, 80));

        titan_image3.setToolTipText("");
        titan_image3.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 80, 80));

        titan_image2.setToolTipText("");
        titan_image2.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 80, 80));

        titan_image4.setToolTipText("");
        titan_image4.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image4, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 120, 80, 80));

        titan_image8.setToolTipText("");
        titan_image8.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image8, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 290, 80, 80));

        titan_image5.setToolTipText("");
        titan_image5.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, 80, 80));

        titan_image7.setToolTipText("");
        titan_image7.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 290, 80, 80));

        btnTitan2_Player1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan2.add(btnTitan2_Player1);
        btnTitan2_Player1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan2_Player1.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan2_Player1.setText("Player 1");
        btnTitan2_Player1.setOpaque(false);
        btnTitan2_Player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitan2_Player1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTitan2_Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 90, -1));

        btnTitan5_Player1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan5.add(btnTitan5_Player1);
        btnTitan5_Player1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan5_Player1.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan5_Player1.setText("Player 1");
        btnTitan5_Player1.setOpaque(false);
        getContentPane().add(btnTitan5_Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 90, -1));

        btnTitan3_Player1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan3.add(btnTitan3_Player1);
        btnTitan3_Player1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan3_Player1.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan3_Player1.setText("Player 1");
        btnTitan3_Player1.setOpaque(false);
        btnTitan3_Player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitan3_Player1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTitan3_Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, 90, -1));

        btnTitan4_Player1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan4.add(btnTitan4_Player1);
        btnTitan4_Player1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan4_Player1.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan4_Player1.setText("Player 1");
        btnTitan4_Player1.setOpaque(false);
        getContentPane().add(btnTitan4_Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 210, 90, -1));

        btnTitan6_Player1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan6.add(btnTitan6_Player1);
        btnTitan6_Player1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan6_Player1.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan6_Player1.setText("Player 1");
        btnTitan6_Player1.setOpaque(false);
        getContentPane().add(btnTitan6_Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, 90, -1));

        btnTitan7_Player1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan7.add(btnTitan7_Player1);
        btnTitan7_Player1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan7_Player1.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan7_Player1.setText("Player 1");
        btnTitan7_Player1.setOpaque(false);
        getContentPane().add(btnTitan7_Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 380, 90, -1));

        btnTitan8_Player1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan8.add(btnTitan8_Player1);
        btnTitan8_Player1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan8_Player1.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan8_Player1.setText("Player 1");
        btnTitan8_Player1.setOpaque(false);
        getContentPane().add(btnTitan8_Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 380, 90, -1));

        btnTitan1_Player1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan1.add(btnTitan1_Player1);
        btnTitan1_Player1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan1_Player1.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan1_Player1.setText("Player 1");
        btnTitan1_Player1.setOpaque(false);
        getContentPane().add(btnTitan1_Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, 90, -1));

        btnTitan2_Player2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan2.add(btnTitan2_Player2);
        btnTitan2_Player2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan2_Player2.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan2_Player2.setText("Player 2");
        btnTitan2_Player2.setOpaque(false);
        btnTitan2_Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitan2_Player2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTitan2_Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 90, -1));

        btnTitan3_Player2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan3.add(btnTitan3_Player2);
        btnTitan3_Player2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan3_Player2.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan3_Player2.setText("Player 2");
        btnTitan3_Player2.setOpaque(false);
        btnTitan3_Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitan3_Player2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTitan3_Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 240, 90, -1));

        btnTitan4_Player2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan4.add(btnTitan4_Player2);
        btnTitan4_Player2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan4_Player2.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan4_Player2.setText("Player 2");
        btnTitan4_Player2.setOpaque(false);
        btnTitan4_Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitan4_Player2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTitan4_Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 240, 90, -1));

        btnTitan5_Player2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan5.add(btnTitan5_Player2);
        btnTitan5_Player2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan5_Player2.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan5_Player2.setText("Player 2");
        btnTitan5_Player2.setOpaque(false);
        btnTitan5_Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitan5_Player2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTitan5_Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 410, 90, -1));

        btnTitan6_Player2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan6.add(btnTitan6_Player2);
        btnTitan6_Player2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan6_Player2.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan6_Player2.setText("Player 2");
        btnTitan6_Player2.setOpaque(false);
        btnTitan6_Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitan6_Player2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTitan6_Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 90, -1));

        btnTitan7_Player2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan7.add(btnTitan7_Player2);
        btnTitan7_Player2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan7_Player2.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan7_Player2.setText("Player 2");
        btnTitan7_Player2.setOpaque(false);
        btnTitan7_Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitan7_Player2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTitan7_Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 90, -1));

        btnTitan8_Player2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan8.add(btnTitan8_Player2);
        btnTitan8_Player2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan8_Player2.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan8_Player2.setText("Player 2");
        btnTitan8_Player2.setOpaque(false);
        btnTitan8_Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitan8_Player2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTitan8_Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 410, 90, -1));

        btnTitan1_Player2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan1.add(btnTitan1_Player2);
        btnTitan1_Player2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan1_Player2.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan1_Player2.setText("Player 2");
        btnTitan1_Player2.setOpaque(false);
        btnTitan1_Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitan1_Player2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTitan1_Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, 90, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Size of Map:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 70, -1, -1));

        cmbSizeofmap.setBackground(new java.awt.Color(0, 0, 0));
        cmbSizeofmap.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmbSizeofmap.setForeground(new java.awt.Color(255, 255, 255));
        cmbSizeofmap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Medium", "Large", " " }));
        getContentPane().add(cmbSizeofmap, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 110, 200, 40));

        lblBackground.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pk/codeapp/tools/SelectTitan_Background.jpg"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTitan2_Player1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitan2_Player1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTitan2_Player1ActionPerformed

    private void btnTitan3_Player1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitan3_Player1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTitan3_Player1ActionPerformed

    private void btnTitan2_Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitan2_Player2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTitan2_Player2ActionPerformed

    private void btnTitan3_Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitan3_Player2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTitan3_Player2ActionPerformed

    private void btnTitan4_Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitan4_Player2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTitan4_Player2ActionPerformed

    private void btnTitan5_Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitan5_Player2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTitan5_Player2ActionPerformed

    private void btnTitan6_Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitan6_Player2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTitan6_Player2ActionPerformed

    private void btnTitan7_Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitan7_Player2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTitan7_Player2ActionPerformed

    private void btnTitan8_Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitan8_Player2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTitan8_Player2ActionPerformed

    private void btnTitan1_Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitan1_Player2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTitan1_Player2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectTitan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectTitan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectTitan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectTitan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectTitan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnTitan1_Player1;
    private javax.swing.JRadioButton btnTitan1_Player2;
    private javax.swing.JRadioButton btnTitan2_Player1;
    private javax.swing.JRadioButton btnTitan2_Player2;
    private javax.swing.JRadioButton btnTitan3_Player1;
    private javax.swing.JRadioButton btnTitan3_Player2;
    private javax.swing.JRadioButton btnTitan4_Player1;
    private javax.swing.JRadioButton btnTitan4_Player2;
    private javax.swing.JRadioButton btnTitan5_Player1;
    private javax.swing.JRadioButton btnTitan5_Player2;
    private javax.swing.JRadioButton btnTitan6_Player1;
    private javax.swing.JRadioButton btnTitan6_Player2;
    private javax.swing.JRadioButton btnTitan7_Player1;
    private javax.swing.JRadioButton btnTitan7_Player2;
    private javax.swing.JRadioButton btnTitan8_Player1;
    private javax.swing.JRadioButton btnTitan8_Player2;
    private javax.swing.ButtonGroup buttonGroupTitan1;
    private javax.swing.ButtonGroup buttonGroupTitan2;
    private javax.swing.ButtonGroup buttonGroupTitan3;
    private javax.swing.ButtonGroup buttonGroupTitan4;
    private javax.swing.ButtonGroup buttonGroupTitan5;
    private javax.swing.ButtonGroup buttonGroupTitan6;
    private javax.swing.ButtonGroup buttonGroupTitan7;
    private javax.swing.ButtonGroup buttonGroupTitan8;
    private javax.swing.JComboBox<String> cmbSizeofmap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel titan_image1;
    private javax.swing.JLabel titan_image2;
    private javax.swing.JLabel titan_image3;
    private javax.swing.JLabel titan_image4;
    private javax.swing.JLabel titan_image5;
    private javax.swing.JLabel titan_image6;
    private javax.swing.JLabel titan_image7;
    private javax.swing.JLabel titan_image8;
    // End of variables declaration//GEN-END:variables
}
