/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pk.codeapp.screen;

import javafx.scene.control.RadioButton;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JRadioButton;
import pk.codeapp.methods.DefaultRules;
import pk.codeapp.model.Titan;

public class SelectTitan extends javax.swing.JFrame implements DefaultRules{
    //Inicialization of Variables
    private int columnGame,rowGame; // Column and row of Table Game
    private boolean activateButtonTowers=true; // Activations of towers button
    private  int minimumTitan=0; // Minimum titans to the players has selected
    private String elementOfArena; 
    private Titan[] titans;
    private Lobby lobby;
    
    public SelectTitan() {
        initComponents(); 
       lblBackground.setIcon(new ImageIcon("src/pk/codeapp/tools/SelectTitan_Background.jpg")); // Image Background 
       this.setLocationRelativeTo(null); //Localization of Windows
       titans=MainApp.methods.getTitans();
        System.out.println(titans);
       putImageIconTitan();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupTitan1 = new javax.swing.ButtonGroup();
        buttonGroupTitan2 = new javax.swing.ButtonGroup();
        buttonGroupTitan3 = new javax.swing.ButtonGroup();
        buttonGroupTitan4 = new javax.swing.ButtonGroup();
        buttonGroupTitan5 = new javax.swing.ButtonGroup();
        buttonGroupTitan6 = new javax.swing.ButtonGroup();
        buttonGroupTitan7 = new javax.swing.ButtonGroup();
        buttonGroupTitan8 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        titan_image6 = new javax.swing.JLabel();
        titan_image1 = new javax.swing.JLabel();
        titan_image3 = new javax.swing.JLabel();
        titan_image2 = new javax.swing.JLabel();
        titan_image4 = new javax.swing.JLabel();
        titan_image8 = new javax.swing.JLabel();
        titan_image5 = new javax.swing.JLabel();
        titan_image7 = new javax.swing.JLabel();
        btnTitan2_Player1 = new javax.swing.JRadioButton();
        btnTitan5_Player1 = new javax.swing.JRadioButton();
        btnTitan3_Player1 = new javax.swing.JRadioButton();
        btnTitan4_Player1 = new javax.swing.JRadioButton();
        btnTitan6_Player1 = new javax.swing.JRadioButton();
        btnTitan7_Player1 = new javax.swing.JRadioButton();
        btnTitan8_Player1 = new javax.swing.JRadioButton();
        btnTitan1_Player1 = new javax.swing.JRadioButton();
        btnTitan2_Player2 = new javax.swing.JRadioButton();
        btnTitan3_Player2 = new javax.swing.JRadioButton();
        btnTitan4_Player2 = new javax.swing.JRadioButton();
        btnTitan5_Player2 = new javax.swing.JRadioButton();
        btnTitan6_Player2 = new javax.swing.JRadioButton();
        btnTitan7_Player2 = new javax.swing.JRadioButton();
        btnTitan8_Player2 = new javax.swing.JRadioButton();
        btnTitan1_Player2 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        cmbSizeofmap = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnPositionTower = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnStartGame = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbSizeofmap1 = new javax.swing.JComboBox<>();
        lblBackground = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select the Titans");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 290, 50));

        titan_image6.setToolTipText("");
        titan_image6.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 80, 80));

        titan_image1.setToolTipText("");
        titan_image1.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 80, 80));

        titan_image3.setToolTipText("");
        titan_image3.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 80, 80));

        titan_image2.setToolTipText("");
        titan_image2.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 80, 80));

        titan_image4.setToolTipText("");
        titan_image4.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 80, 80));

        titan_image8.setToolTipText("");
        titan_image8.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 80, 80));

        titan_image5.setToolTipText("");
        titan_image5.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 80, 80));

        titan_image7.setToolTipText("");
        titan_image7.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 80, 80));

        btnTitan2_Player1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan2.add(btnTitan2_Player1);
        btnTitan2_Player1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan2_Player1.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan2_Player1.setText("Player 1");
        btnTitan2_Player1.setOpaque(false);
        btnTitan2_Player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitan2_Player1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTitan2_Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 90, -1));

        btnTitan5_Player1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan5.add(btnTitan5_Player1);
        btnTitan5_Player1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan5_Player1.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan5_Player1.setText("Player 1");
        btnTitan5_Player1.setOpaque(false);
        getContentPane().add(btnTitan5_Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 420, 90, -1));

        btnTitan3_Player1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan3.add(btnTitan3_Player1);
        btnTitan3_Player1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan3_Player1.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan3_Player1.setText("Player 1");
        btnTitan3_Player1.setOpaque(false);
        btnTitan3_Player1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitan3_Player1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTitan3_Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 250, 90, -1));

        btnTitan4_Player1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan4.add(btnTitan4_Player1);
        btnTitan4_Player1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan4_Player1.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan4_Player1.setText("Player 1");
        btnTitan4_Player1.setOpaque(false);
        getContentPane().add(btnTitan4_Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 90, -1));

        btnTitan6_Player1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan6.add(btnTitan6_Player1);
        btnTitan6_Player1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan6_Player1.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan6_Player1.setText("Player 1");
        btnTitan6_Player1.setOpaque(false);
        getContentPane().add(btnTitan6_Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 420, 90, -1));

        btnTitan7_Player1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan7.add(btnTitan7_Player1);
        btnTitan7_Player1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan7_Player1.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan7_Player1.setText("Player 1");
        btnTitan7_Player1.setOpaque(false);
        getContentPane().add(btnTitan7_Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 420, 90, -1));

        btnTitan8_Player1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan8.add(btnTitan8_Player1);
        btnTitan8_Player1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan8_Player1.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan8_Player1.setText("Player 1");
        btnTitan8_Player1.setOpaque(false);
        getContentPane().add(btnTitan8_Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, 90, -1));

        btnTitan1_Player1.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan1.add(btnTitan1_Player1);
        btnTitan1_Player1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan1_Player1.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan1_Player1.setText("Player 1");
        btnTitan1_Player1.setOpaque(false);
        getContentPane().add(btnTitan1_Player1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 90, -1));

        btnTitan2_Player2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan2.add(btnTitan2_Player2);
        btnTitan2_Player2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan2_Player2.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan2_Player2.setText("Player 2");
        btnTitan2_Player2.setOpaque(false);
        btnTitan2_Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitan2_Player2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTitan2_Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 90, -1));

        btnTitan3_Player2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan3.add(btnTitan3_Player2);
        btnTitan3_Player2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan3_Player2.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan3_Player2.setText("Player 2");
        btnTitan3_Player2.setOpaque(false);
        btnTitan3_Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitan3_Player2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTitan3_Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 280, 90, -1));

        btnTitan4_Player2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan4.add(btnTitan4_Player2);
        btnTitan4_Player2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan4_Player2.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan4_Player2.setText("Player 2");
        btnTitan4_Player2.setOpaque(false);
        btnTitan4_Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitan4_Player2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTitan4_Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 280, 90, -1));

        btnTitan5_Player2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan5.add(btnTitan5_Player2);
        btnTitan5_Player2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan5_Player2.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan5_Player2.setText("Player 2");
        btnTitan5_Player2.setOpaque(false);
        btnTitan5_Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitan5_Player2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTitan5_Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, 90, -1));

        btnTitan6_Player2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan6.add(btnTitan6_Player2);
        btnTitan6_Player2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan6_Player2.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan6_Player2.setText("Player 2");
        btnTitan6_Player2.setOpaque(false);
        btnTitan6_Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitan6_Player2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTitan6_Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 90, -1));

        btnTitan7_Player2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan7.add(btnTitan7_Player2);
        btnTitan7_Player2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan7_Player2.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan7_Player2.setText("Player 2");
        btnTitan7_Player2.setOpaque(false);
        btnTitan7_Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitan7_Player2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTitan7_Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 90, -1));

        btnTitan8_Player2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan8.add(btnTitan8_Player2);
        btnTitan8_Player2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan8_Player2.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan8_Player2.setText("Player 2");
        btnTitan8_Player2.setOpaque(false);
        btnTitan8_Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitan8_Player2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTitan8_Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 450, 90, -1));

        btnTitan1_Player2.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroupTitan1.add(btnTitan1_Player2);
        btnTitan1_Player2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnTitan1_Player2.setForeground(new java.awt.Color(255, 255, 255));
        btnTitan1_Player2.setText("Player 2");
        btnTitan1_Player2.setOpaque(false);
        btnTitan1_Player2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTitan1_Player2ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTitan1_Player2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, 90, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Choose the element arena");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 380, -1, -1));

        cmbSizeofmap.setBackground(new java.awt.Color(0, 0, 0));
        cmbSizeofmap.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmbSizeofmap.setForeground(new java.awt.Color(255, 255, 255));
        cmbSizeofmap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Medium", "Large", " " }));
        getContentPane().add(cmbSizeofmap, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 110, 200, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Selection Position Tower:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 230, -1, -1));

        btnPositionTower.setBackground(new java.awt.Color(0, 0, 0));
        btnPositionTower.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnPositionTower.setForeground(new java.awt.Color(255, 255, 255));
        btnPositionTower.setText("Position Towers");
        btnPositionTower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPositionTowerActionPerformed(evt);
            }
        });
        getContentPane().add(btnPositionTower, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 270, 160, 60));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 140, 50));

        btnStartGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pk/codeapp/tools/playGame.png"))); // NOI18N
        btnStartGame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartGameActionPerformed(evt);
            }
        });
        getContentPane().add(btnStartGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 570, 200, 90));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Size of Map:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 70, -1, -1));

        cmbSizeofmap1.setBackground(new java.awt.Color(0, 0, 0));
        cmbSizeofmap1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmbSizeofmap1.setForeground(new java.awt.Color(255, 255, 255));
        cmbSizeofmap1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fire", "Aqua", "Wind", "Land", " " }));
        getContentPane().add(cmbSizeofmap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 420, 200, 40));

        lblBackground.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pk/codeapp/tools/SelectTitan_Background.jpg"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTitan2_Player1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitan2_Player1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTitan2_Player1ActionPerformed

    private void btnTitan3_Player1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitan3_Player1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTitan3_Player1ActionPerformed

    private void btnTitan2_Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitan2_Player2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTitan2_Player2ActionPerformed

    private void btnTitan3_Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitan3_Player2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTitan3_Player2ActionPerformed

    private void btnTitan4_Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitan4_Player2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTitan4_Player2ActionPerformed

    private void btnTitan5_Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitan5_Player2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTitan5_Player2ActionPerformed

    private void btnTitan6_Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitan6_Player2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTitan6_Player2ActionPerformed

    private void btnTitan7_Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitan7_Player2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTitan7_Player2ActionPerformed

    private void btnTitan8_Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitan8_Player2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTitan8_Player2ActionPerformed

    private void btnTitan1_Player2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTitan1_Player2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTitan1_Player2ActionPerformed

    private void btnPositionTowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPositionTowerActionPerformed
        if(activateButtonTowers){
        String sizeOfTable = checkStringSize(); // Return the string of combobox
        setSizeoftableGame(sizeOfTable); //set variables column and row related to String size
        this.setVisible(false);
        
        // Set ColumnGame and RowGame in methods
        MainApp.methods.setColumnGame(columnGame);
        MainApp.methods.setRowGame(rowGame);
        
        SelectionTower selectionTower =  new SelectionTower(); //Instance of windows selection of tower
        this.setVisible(false);
        selectionTower.openWindow(this); // Pass windows to Selection of tower
        activateButtonTowers=false; //Desactive button
        }
    }//GEN-LAST:event_btnPositionTowerActionPerformed
    private void putImageIconTitan(){ // Put icons of titans in the labels
        titans = MainApp.methods.getTitans();
        System.out.println(titans);
        for (int i = 0; i < titans.length; i++) {
           if(titans[i]!=null){
                 
                JLabel aux=checkIconJLabel(i+1);
                if(aux==null)
                    break;
                else    
                    aux.setIcon(titans[i].getIcon());                
        }
        }
    }
    private JLabel checkIconJLabel(int i){ // Return the JLabel 
        switch(i){
        case 1: return titan_image1;
        case 2:return titan_image2;
        case 3:return titan_image3;
        case 4:return titan_image4;
        case 5 :return titan_image5;
        case 6:return titan_image6;
        case 7:return titan_image7;
        case 8:return titan_image8;
        }
        return null;  
    }
    //Button to Start Game 
    private void btnStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartGameActionPerformed
        if(activateButtonTowers==true){ //Checks to tower is correct selected
            JOptionPane.showMessageDialog(rootPane, "!!! Select the towers to Play Game !!! ");
        }else{
           if(addTitanInTheCorrectPlayer()){
               setElementOfArena((String)cmbSizeofmap1.getSelectedItem());
               Game game = new Game();
               game.openWindow(this);
               
               
               
           }
               
               
        }
    }//GEN-LAST:event_btnStartGameActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        goBack();
    }//GEN-LAST:event_jButton2ActionPerformed
    private boolean addTitanInTheCorrectPlayer(){ // Add each titan in the correct player with respect to the selected button
         for (int i = 0; i < titans.length; i++) {
                if(minimumTitan<3){ //Checks minimum Titans
                if(titans[i]!=null){
                    System.out.println(getButtonGroup(i).getSelection());
                    if(getButtonGroup(i).getSelection().equals(getRadioButton(i))) //Checks to Group Buttons which Button is selected( in this case buttons to player 1)
                        titans[i].setPlayer("player1"); //add text
                    else
                        titans[i].setPlayer("player2"); //add text
                }
                else{
                    minimumTitan++;// if is null plus one 
                }}
                else{
                    JOptionPane.showMessageDialog(rootPane,"The minimum Titans is 6, Please select more Titan(s)");
                    return false;
                }
                
            }return true;
    }
    private JRadioButton getRadioButton(int i){// Return RadioButton  and give num(1-8)
        switch("btnTitan"+i+"_Player1"){
            case "btnTitan1_Player1": return btnTitan1_Player1;
            case "btnTitan2_Player1":return btnTitan2_Player1;
            case "btnTitan3_Player1":return btnTitan3_Player1;
            case "btnTitan4_Player1":return btnTitan4_Player1;
            case "btnTitan5_Player1":return btnTitan5_Player1;
            case "btnTitan6_Player1":return btnTitan6_Player1;
            case "btnTitan7_Player1":return btnTitan7_Player1;
            case "btnTitan8_Player1":return btnTitan8_Player1;
        }
        return null;
    }
    private ButtonGroup getButtonGroup(int i){ // Return GroupButton  and give num(1-8)
        switch("buttonGroupTitan"+i){
            case "buttonGroupTitan1": return buttonGroupTitan1;
            case "buttonGroupTitan2":return buttonGroupTitan2;
            case "buttonGroupTitan3":return buttonGroupTitan3;
            case "buttonGroupTitan4":return buttonGroupTitan4;
            case "buttonGroupTitan5":return buttonGroupTitan5;
            case "buttonGroupTitan6":return buttonGroupTitan6;
            case "buttonGroupTitan7":return buttonGroupTitan7;
            case "buttonGroupTitan8":return buttonGroupTitan8;
        }
        return null;
    }
    private String checkStringSize(){ // Return the String cliked in cmb (Small,Medium,Large)
        return (String)cmbSizeofmap.getSelectedItem(); 
    }
    private void setSizeoftableGame(String sizeOfTable){
        if(sizeOfTable.equals("Large")){
            this.columnGame=14;
            this.rowGame=15;}
        else if(sizeOfTable.equals("Medium")){
            this.columnGame=12;
            this.rowGame=13;
        }else{
            this.columnGame=10;
            this.rowGame=11;
        }  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectTitan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectTitan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectTitan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectTitan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectTitan().setVisible(true);
            }
        });
    }
      // <editor-fold defaultstate="collapsed" desc="Geters and Seters">

    public String getElementOfArena() {
        return elementOfArena;
    }

    public void setElementOfArena(String elementOfArena) {
        this.elementOfArena = elementOfArena;
    }
    
    public int getColumnGame() {
        return columnGame;
    }

    public void setColumnGame(int columnGame) {
        this.columnGame = columnGame;
    }

    public int getRowGame() {
        return rowGame;
    }

    public void setRowGame(int rowGame) {
        this.rowGame = rowGame;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPositionTower;
    private javax.swing.JButton btnStartGame;
    private javax.swing.JRadioButton btnTitan1_Player1;
    private javax.swing.JRadioButton btnTitan1_Player2;
    private javax.swing.JRadioButton btnTitan2_Player1;
    private javax.swing.JRadioButton btnTitan2_Player2;
    private javax.swing.JRadioButton btnTitan3_Player1;
    private javax.swing.JRadioButton btnTitan3_Player2;
    private javax.swing.JRadioButton btnTitan4_Player1;
    private javax.swing.JRadioButton btnTitan4_Player2;
    private javax.swing.JRadioButton btnTitan5_Player1;
    private javax.swing.JRadioButton btnTitan5_Player2;
    private javax.swing.JRadioButton btnTitan6_Player1;
    private javax.swing.JRadioButton btnTitan6_Player2;
    private javax.swing.JRadioButton btnTitan7_Player1;
    private javax.swing.JRadioButton btnTitan7_Player2;
    private javax.swing.JRadioButton btnTitan8_Player1;
    private javax.swing.JRadioButton btnTitan8_Player2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroupTitan1;
    private javax.swing.ButtonGroup buttonGroupTitan2;
    private javax.swing.ButtonGroup buttonGroupTitan3;
    private javax.swing.ButtonGroup buttonGroupTitan4;
    private javax.swing.ButtonGroup buttonGroupTitan5;
    private javax.swing.ButtonGroup buttonGroupTitan6;
    private javax.swing.ButtonGroup buttonGroupTitan7;
    private javax.swing.ButtonGroup buttonGroupTitan8;
    private javax.swing.JComboBox<String> cmbSizeofmap;
    private javax.swing.JComboBox<String> cmbSizeofmap1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel titan_image1;
    private javax.swing.JLabel titan_image2;
    private javax.swing.JLabel titan_image3;
    private javax.swing.JLabel titan_image4;
    private javax.swing.JLabel titan_image5;
    private javax.swing.JLabel titan_image6;
    private javax.swing.JLabel titan_image7;
    private javax.swing.JLabel titan_image8;
    // End of variables declaration//GEN-END:variables

    @Override
    public void openWindow(JFrame frame) {
       lobby=(Lobby)frame;
       this.setVisible(true);
       lobby.setVisible(false);
    }
     public void openWindows(JFrame frame) {
       lobby=(Lobby)frame;
       lobby.setVisible(false);
       this.setVisible(true);
       
    }
    @Override
    public void goBack() {
        this.dispose();
        lobby.setVisible(true);
    }

   
    
}

