/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pk.codeapp.screen;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import pk.codeapp.methods.DefaultRules;
import pk.codeapp.model.GraphicsElement;
import pk.codeapp.model.Titan;
import static pk.codeapp.screen.MainApp.methods;

public class SelectTitan extends javax.swing.JFrame implements DefaultRules
{

    //Inicialization of Variables
    private int columnGame, rowGame; // Column and row of Table Game
    private boolean activateButtonTowers = true; // Activations of towers button
    private int minimumTitan = 0; // Minimum titans to the players has selected
    private String elementOfArena;
    private Titan[] titans;
    private Lobby lobby;
    private int contTitansPlayer1 = 4;
    private int contTitansPlayer2 = 4;
    
     SelectionTower selectionTower;
    public SelectTitan()
    {
        initComponents();
        lblBackground.setIcon(new ImageIcon("src/pk/codeapp/tools/SelectTitan_Background.jpg")); // Image Background 
        this.setLocationRelativeTo(null); //Localization of Windows
        titans = MainApp.methods.getTitans();
        // the visibility of cmb is false
        cmbTitan1.setVisible(false);
        cmbTitan2.setVisible(false);
        cmbTitan3.setVisible(false);
        cmbTitan4.setVisible(false);
        cmbTitan5.setVisible(false);
        cmbTitan6.setVisible(false);
        cmbTitan7.setVisible(false);
        cmbTitan8.setVisible(false);

        putImageIconTitan(); // Put the image in the labels 
        this.addWindowListener(new WindowAdapter()
        {
            public void windowClosing(WindowEvent evt)
            {

                methods.writeUser();
                System.exit(0);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        buttonGroupTitan1 = new javax.swing.ButtonGroup();
        buttonGroupTitan2 = new javax.swing.ButtonGroup();
        buttonGroupTitan3 = new javax.swing.ButtonGroup();
        buttonGroupTitan4 = new javax.swing.ButtonGroup();
        buttonGroupTitan5 = new javax.swing.ButtonGroup();
        buttonGroupTitan6 = new javax.swing.ButtonGroup();
        buttonGroupTitan7 = new javax.swing.ButtonGroup();
        buttonGroupTitan8 = new javax.swing.ButtonGroup();
        jMenu1 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        titan_image6 = new javax.swing.JLabel();
        titan_image1 = new javax.swing.JLabel();
        titan_image3 = new javax.swing.JLabel();
        titan_image2 = new javax.swing.JLabel();
        titan_image4 = new javax.swing.JLabel();
        titan_image8 = new javax.swing.JLabel();
        titan_image5 = new javax.swing.JLabel();
        titan_image7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbSizeofmap = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnPositionTower = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnStartGame = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        cmbSizeofmap1 = new javax.swing.JComboBox<>();
        cmbTitan1 = new javax.swing.JComboBox<>();
        cmbTitan2 = new javax.swing.JComboBox<>();
        cmbTitan3 = new javax.swing.JComboBox<>();
        cmbTitan4 = new javax.swing.JComboBox<>();
        cmbTitan5 = new javax.swing.JComboBox<>();
        cmbTitan6 = new javax.swing.JComboBox<>();
        cmbTitan7 = new javax.swing.JComboBox<>();
        cmbTitan8 = new javax.swing.JComboBox<>();
        lblBackground = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Select the Titans");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, 390, 50));

        titan_image6.setToolTipText("");
        titan_image6.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 330, 80, 80));

        titan_image1.setToolTipText("");
        titan_image1.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 80, 80));

        titan_image3.setToolTipText("");
        titan_image3.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 160, 80, 80));

        titan_image2.setToolTipText("");
        titan_image2.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 80, 80));

        titan_image4.setToolTipText("");
        titan_image4.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 80, 80));

        titan_image8.setToolTipText("");
        titan_image8.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 330, 80, 80));

        titan_image5.setToolTipText("");
        titan_image5.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 80, 80));

        titan_image7.setToolTipText("");
        titan_image7.setBorder(new javax.swing.border.MatteBorder(null));
        getContentPane().add(titan_image7, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 80, 80));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("3.Choose the element arena");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 380, -1, -1));

        cmbSizeofmap.setBackground(new java.awt.Color(0, 0, 0));
        cmbSizeofmap.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmbSizeofmap.setForeground(new java.awt.Color(255, 255, 255));
        cmbSizeofmap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Medium", "Large", " " }));
        cmbSizeofmap.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cmbSizeofmapActionPerformed(evt);
            }
        });
        getContentPane().add(cmbSizeofmap, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 110, 200, 40));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("2.Selection Position Tower:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 230, -1, -1));

        btnPositionTower.setBackground(new java.awt.Color(0, 0, 0));
        btnPositionTower.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnPositionTower.setForeground(new java.awt.Color(255, 255, 255));
        btnPositionTower.setText("Position Towers");
        btnPositionTower.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnPositionTowerActionPerformed(evt);
            }
        });
        getContentPane().add(btnPositionTower, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 270, 160, 60));

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 630, 140, 50));

        btnStartGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pk/codeapp/tools/playGame.png"))); // NOI18N
        btnStartGame.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnStartGameActionPerformed(evt);
            }
        });
        getContentPane().add(btnStartGame, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 580, 200, 90));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("1.Size of Map:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 70, -1, -1));

        cmbSizeofmap1.setBackground(new java.awt.Color(0, 0, 0));
        cmbSizeofmap1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        cmbSizeofmap1.setForeground(new java.awt.Color(255, 255, 255));
        cmbSizeofmap1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fire", "Aqua", "Wind", "Land" }));
        getContentPane().add(cmbSizeofmap1, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 420, 200, 40));

        cmbTitan1.setBackground(new java.awt.Color(0, 0, 0));
        cmbTitan1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmbTitan1.setForeground(new java.awt.Color(255, 255, 255));
        cmbTitan1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Player1", "Player2" }));
        getContentPane().add(cmbTitan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 100, 30));

        cmbTitan2.setBackground(new java.awt.Color(0, 0, 0));
        cmbTitan2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmbTitan2.setForeground(new java.awt.Color(255, 255, 255));
        cmbTitan2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Player1", "Player2" }));
        getContentPane().add(cmbTitan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, 100, 30));

        cmbTitan3.setBackground(new java.awt.Color(0, 0, 0));
        cmbTitan3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmbTitan3.setForeground(new java.awt.Color(255, 255, 255));
        cmbTitan3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Player1", "Player2" }));
        getContentPane().add(cmbTitan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 100, 30));

        cmbTitan4.setBackground(new java.awt.Color(0, 0, 0));
        cmbTitan4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmbTitan4.setForeground(new java.awt.Color(255, 255, 255));
        cmbTitan4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Player1", "Player2" }));
        getContentPane().add(cmbTitan4, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 250, 100, 30));

        cmbTitan5.setBackground(new java.awt.Color(0, 0, 0));
        cmbTitan5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmbTitan5.setForeground(new java.awt.Color(255, 255, 255));
        cmbTitan5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Player1", "Player2" }));
        getContentPane().add(cmbTitan5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 420, 100, 30));

        cmbTitan6.setBackground(new java.awt.Color(0, 0, 0));
        cmbTitan6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmbTitan6.setForeground(new java.awt.Color(255, 255, 255));
        cmbTitan6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Player1", "Player2" }));
        getContentPane().add(cmbTitan6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 100, 30));

        cmbTitan7.setBackground(new java.awt.Color(0, 0, 0));
        cmbTitan7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmbTitan7.setForeground(new java.awt.Color(255, 255, 255));
        cmbTitan7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Player1", "Player2" }));
        getContentPane().add(cmbTitan7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 420, 100, 30));

        cmbTitan8.setBackground(new java.awt.Color(0, 0, 0));
        cmbTitan8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cmbTitan8.setForeground(new java.awt.Color(255, 255, 255));
        cmbTitan8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Player1", "Player2" }));
        getContentPane().add(cmbTitan8, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 420, 100, 30));

        lblBackground.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pk/codeapp/tools/SelectTitan_Background.jpg"))); // NOI18N
        getContentPane().add(lblBackground, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPositionTowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPositionTowerActionPerformed
        if (activateButtonTowers) {
            cmbSizeofmap.setEnabled(false);
            String sizeOfTable = checkStringSize(); // Return the string of combobox
            setSizeoftableGame(sizeOfTable); //set variables column and row related to String size
            this.setVisible(false);

            // Set ColumnGame and RowGame in methods
            MainApp.methods.setColumnGame(columnGame);
            MainApp.methods.setRowGame(rowGame);

            selectionTower = new SelectionTower(); //Instance of windows selection of tower
            this.setVisible(false);
            selectionTower.openWindow(this); // Pass windows to Selection of tower
            
            activateButtonTowers = false; //Desactive button
        }
    }//GEN-LAST:event_btnPositionTowerActionPerformed
    private void putImageIconTitan()
    { // Put icons of titans in the labels
        for (int i = 0; i < titans.length; i++) {
            if (titans[i] != null) {
                JLabel aux = checkIconJLabel(i + 1);
                if (aux != null) {
                    getcmbTitan(i + 1).setVisible(true);
                    aux.setIcon(titans[i].getIcon());
                }
            }
        }
    }

    private JLabel checkIconJLabel(int i)
    { // Return the JLabel 
        switch (i) {
            case 1:
                return titan_image1;
            case 2:
                return titan_image2;
            case 3:
                return titan_image3;
            case 4:
                return titan_image4;
            case 5:
                return titan_image5;
            case 6:
                return titan_image6;
            case 7:
                return titan_image7;
            case 8:
                return titan_image8;
        }
        return null;
    }

    //Button to Start Game 
    private void btnStartGameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartGameActionPerformed
        if (activateButtonTowers == true) { //Checks to tower is correct selected
            JOptionPane.showMessageDialog(rootPane, "!!! Select the towers to Play Game !!! ");
        } else {

            addTitanInTheCorrectPlayer();
            if (contTitansPlayer1 < 2 && contTitansPlayer2 < 2) {
                String elementofArena = (String) cmbSizeofmap1.getSelectedItem();
                setElementOfArena(elementofArena);
                Game game = new Game();
                game.obtainQuantityTower(selectionTower.getContTowersP1(),selectionTower.getContTowersP2());
                game.openWindow(this);
               

            } else {
                contTitansPlayer1 = 4;
                contTitansPlayer2 = 4;
                JOptionPane.showMessageDialog(rootPane, "You need more Titans to pay, minimun 3 for player");
            }

        }
    }//GEN-LAST:event_btnStartGameActionPerformed
    private JComboBox getcmbTitan(int i)
    {
        switch (i) {
            case 1:
                return cmbTitan1;
            case 2:
                return cmbTitan2;
            case 3:
                return cmbTitan3;
            case 4:
                return cmbTitan4;
            case 5:
                return cmbTitan5;
            case 6:
                return cmbTitan6;
            case 7:
                return cmbTitan7;
            case 8:
                return cmbTitan8;
        }
        return null;
    }
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MainApp.methods.setGraphicsElements(null);
        goBack();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cmbSizeofmapActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cmbSizeofmapActionPerformed
    {//GEN-HEADEREND:event_cmbSizeofmapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSizeofmapActionPerformed
    private boolean addTitanInTheCorrectPlayer()
    { // Add each titan in the correct player with respect to the selected button
        titans = MainApp.methods.getTitans();
        for (int i = 0; i < titans.length; i++) {
            if (titans[i] != null) {
                JComboBox cmb = getcmbTitan(i + 1);
                if (cmb == null) {
                    break;
                } else {
                    int player = cmb.getSelectedIndex();
                    if (player == 1) {
                        titans[i].setPlayer("Player2");
                        contTitansPlayer1--;
                    } else {
                        titans[i].setPlayer("Player1");
                        contTitansPlayer2--;
                    }
                }
            }
        }
        // Checks number of selected players
        if (contTitansPlayer1 > 2) {
            return false;
        } else {
            if (contTitansPlayer2 > 2) {
                return false;
            }
        }
        return true;
    }

    private String checkStringSize()
    { // Return the String cliked in cmb (Small,Medium,Large)
        return (String) cmbSizeofmap.getSelectedItem();
    }

    private void setSizeoftableGame(String sizeOfTable)
    { // storage column and row 
        System.out.println(sizeOfTable);
        if (sizeOfTable.equals("Large")) {
            this.columnGame = 14;
            this.rowGame = 14;
        } else if (sizeOfTable.equals("Medium")) {
            this.columnGame = 12;
            this.rowGame = 12;
        } else {
            this.columnGame = 10;
            this.rowGame = 10;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectTitan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectTitan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectTitan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectTitan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new SelectTitan().setVisible(true);
            }
        });
    }
    // <editor-fold defaultstate="collapsed" desc="Geters and Seters">

    public String getElementOfArena()
    {
        return elementOfArena;
    }

    public void setElementOfArena(String elementOfArena)
    {
        this.elementOfArena = elementOfArena;
    }

    public int getColumnGame()
    {
        return columnGame;
    }

    public void setColumnGame(int columnGame)
    {
        this.columnGame = columnGame;
    }

    public int getRowGame()
    {
        return rowGame;
    }

    public void setRowGame(int rowGame)
    {
        this.rowGame = rowGame;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPositionTower;
    private javax.swing.JButton btnStartGame;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroupTitan1;
    private javax.swing.ButtonGroup buttonGroupTitan2;
    private javax.swing.ButtonGroup buttonGroupTitan3;
    private javax.swing.ButtonGroup buttonGroupTitan4;
    private javax.swing.ButtonGroup buttonGroupTitan5;
    private javax.swing.ButtonGroup buttonGroupTitan6;
    private javax.swing.ButtonGroup buttonGroupTitan7;
    private javax.swing.ButtonGroup buttonGroupTitan8;
    private javax.swing.JComboBox<String> cmbSizeofmap;
    private javax.swing.JComboBox<String> cmbSizeofmap1;
    private javax.swing.JComboBox<String> cmbTitan1;
    private javax.swing.JComboBox<String> cmbTitan2;
    private javax.swing.JComboBox<String> cmbTitan3;
    private javax.swing.JComboBox<String> cmbTitan4;
    private javax.swing.JComboBox<String> cmbTitan5;
    private javax.swing.JComboBox<String> cmbTitan6;
    private javax.swing.JComboBox<String> cmbTitan7;
    private javax.swing.JComboBox<String> cmbTitan8;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JLabel lblBackground;
    private javax.swing.JLabel titan_image1;
    private javax.swing.JLabel titan_image2;
    private javax.swing.JLabel titan_image3;
    private javax.swing.JLabel titan_image4;
    private javax.swing.JLabel titan_image5;
    private javax.swing.JLabel titan_image6;
    private javax.swing.JLabel titan_image7;
    private javax.swing.JLabel titan_image8;
    // End of variables declaration//GEN-END:variables

    @Override
    public void openWindow(JFrame frame)
    {
        lobby = (Lobby) frame;
        this.setVisible(true);
        lobby.setVisible(false);
    }

    public void openWindows(JFrame frame)
    {
        lobby = (Lobby) frame;
        lobby.setVisible(false);
        this.setVisible(true);

    }

    @Override
    public void goBack()
    {
        this.dispose();
        lobby.setVisible(true);
    }

}
